### ISSUE TITLE
how to set Different redirect uri in Client

### ISSUE THREAD

**Issue by Cloud9InfoIndia** [DuendeSoftware/Support#62]
Hi

I am using Identity Server 4 for SSO implementation in my project. I am storing Registered client configurations in IDs store DB. Storing values like ClientID, secret, Grant type(implicit, auth code, password etc), redirect and postlogout redirect uris

Usually for any client or MVC client we set redirect Uri as https://{Clientapplicationurl}/signin-oidc as a standard callback path and routing to client page happens through signin-oidc.

But I have a different requirement for one of the client as:
When client user successfully log into application they should land on this page - **[https://{applicationurl}/test/main/StartPage.aspx?Type=Primary?date=somedate]**
How do we specify signin-oidc for this redirect URL ? or basically how to set redirect uri or how to do the redirection in such scenario. Be it a MVC client or Java client or SPA client
what is a standard way of setting such redirect Uris

Please suggest at the earliest.

Thanks.

**Comment by brockallen** [comment]
>  When client user successfully log into application they should land on this page - [https://{applicationurl}/test/main/StartPage.aspx?Type=Primary?date=somedate]
> How do we specify signin-oidc for this redirect URL

Any params in the URL that you want to preserve across the OIDC signin request/response should be preserved as state client-side prior to the redirect away, and restored after the response back. If you're using ASP.NET Core or Katana then those frameworks from Microsoft do this for you, assuming you set the `ReturnUrl` on the `AuthenticationProperties` that your logic passes to `Challenge`.

**Comment by Cloud9InfoIndia** [comment]
Ok. Thanks for the response. But how do I set redirect Uri value with signin-oidc callback for the registered client ? should it be like **[https://{applicationurl}/test/main/signin-oidc/StartPage.aspx?Type=Primary?date=somedate]** ? or anything different?

**Comment by Cloud9InfoIndia** [comment]
Thanks again for the reply.

But in my case the Authentication request sending page is different and return/response redirect page is different. For example my request initiating page is **https://{clientapplicationurl}/home/index.aspx** with some parameter passed where user clicks on Login to call IDS Authorize endpoint. Here it goes to IDS login page. After user login in and successfully authenticated, user should redirect back to a different page as  **https://{clientapplicationurl}/test/main/StartPage.aspx** should have the same parameter. In this case How should I configure Redirect Uri for my Client? so should I set it like **https://{clientapplicationurl}/test/main/signin-oidc** in client configs in db and the same needs to be set in AuthenticationProperties in Client app? I tried doing that but in that case it does not redirect me to that page
here is my code in Client app configureServices method for OpenIDConnect:
options.Events = new OpenIdConnectEvents
                    {
                        OnRedirectToIdentityProvider = context =>
                        {
                            context.ProtocolMessage.SetParameter("Site",
                            context.Request.Query["site"]);
                            context.ProtocolMessage.RedirectUri = "https://"clientapplicationurl}/test/main/signin-oidc?Type=Primary";
                            return Task.FromResult(0);
                        }
                    };
                    
pls suggest or share code sample.

Thanks

**Comment by brockallen** [comment]
The redirect URI in your app is fixed -- that's a security feature in the protocol so don't try to change that dynamically. ASP.NET provides the AuthenticationProperties to round trip state across that request/response, so you'd need to store the state in there (there's an Items dictionary) and on the redirect back unpack it and do the last step yourself then based on that state. This is so common for the URL you really want to land on, they provide a strongly typed ReturnUrl property on it.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationproperties?view=aspnetcore-6.0

I searched and found this article that also might be helpful: 

https://hajekj.net/2018/06/12/passing-state-through-authentication-in-asp-net-core/

**Comment by Cloud9InfoIndia** [comment]
Sorry to trouble you again. But I am still not clear on how to set Redirect uri for my Client. My main concern is about setting RedirectUri? As I said earlier also, for MVC client we usually set Redirect Uri as **https://localhost:44345/signin-oidc**. so there has to be signin-oidc set in the Uri value. Now if my application is a normal Asp.Net application and I want to redirect client to an .aspx page Ex: **https://{clientapplicationurl}/test/main/StartPage.aspx** then how do I set Redirect Uri value for the Client? does signin-oidc need be present in the Uri? if yes how should I append it? please help give the specific Uri format/syntax

**Comment by Cloud9InfoIndia** [comment]
Hey Brock Allen, thanks for the reply. I helped me in resolving the issue and conclude on the scenario.

But I have another question. Sorry I am asking these questions but I have started exploring Identity server and getting these queries while doing the implementation.
My question is how do we set Redirect Uri for a Java-Tomcat based application? Will it be same as we set for .Net MVC app like https://localhost:44345/signin-oidc? does signin-oidc needed in case of Java-Tomcat application. Also can you share any documentation link where I can get exact answer/resolution/details for my queries as per the tech used in Client application

Thanks.

**Comment by leastprivilege** [comment]
> how do we set Redirect Uri for a Java-Tomcat based application?

Please consult the documentation of the library.
